### ISSUE TITLE
Start Semantic Versioning

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#48]
It will be great provide semver and releases for current stage. What are you thinking about?

**Comment by dcodeIO** [comment]
There are still a couple of very basic things I'd like to implement before publishing. That's for example class inheritance, which is partially supported now, a way to actually free memory and a basic standard library.

**Comment by MaxGraey** [comment]
got it

**Comment by dcodeIO** [comment]
There are still a couple of edge cases that require investigation, but aside from these we should be good for an initial release.

For reference:
* `IMPORT_MALLOC` doesn't work yet because binaryen, for some reason, does not recognize the imported functions and validation fails with a "call target must exist" assertion.
* Optional function arguments are evaluated in the calling context, preventing proper use of `this` here for example.

**Comment by dcodeIO** [comment]
Closing this issue as AssemblyScript is on npm now.
