### ISSUE TITLE
Whole module optimization

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#49]
For code:
```ts
var arr: Array<float32> = new Array<float32>(3);
```

**TurboScript** - 786 Bytes
**AssemblyScript** - 11.74 KB

It seems AssemblyScript include whole **malloc module** after compile with optimization, with ```memcpy``` and ```free```. But we need only ```malloc``` and ```memset```.

**Comment by dcodeIO** [comment]
That's because standard library methods are exported currently under the assumption that the embedder can use them to provide data to the WebAssembly module. It should be trivial though to add an option to prevent them from exporting so that the optimizer can simply optimize them away.

**Comment by dcodeIO** [comment]
There is an option now doing what you want: `internalMalloc: true`

**Comment by dcodeIO** [comment]
Actually, because `mspace_init` (which references `memset`) is called within `start` no matter what, these functions cannot be DCEed in case `malloc` isn't used. The compiler either has to keep track of any uses of `malloc` or, since `malloc: false` hasn't be specified, we can just take this as intended in the unlikely case it is.

**Comment by MaxGraey** [comment]
Yes, I already adopt new config to Assembleash. You can [check](https://maxgraey.github.io/Assembleash/#AssemblyScript)

**Comment by dcodeIO** [comment]
With the additional `asc` options in place now, it should be possible to configure the compile step exactly as required.
